//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUSGrabberGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUSGrabberGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CDecrypt {
            get {
                object obj = ResourceManager.GetObject("CDecrypt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HtmlAgilityPack {
            get {
                object obj = ResourceManager.GetObject("HtmlAgilityPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libeay32 {
            get {
                object obj = ResourceManager.GetObject("libeay32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] msvcp140 {
            get {
                object obj = ResourceManager.GetObject("msvcp140", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] msvcr120 {
            get {
                object obj = ResourceManager.GetObject("msvcr120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NUSgrabber {
            get {
                object obj = ResourceManager.GetObject("NUSgrabber", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vcruntime140 {
            get {
                object obj = ResourceManager.GetObject("vcruntime140", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] wget {
            get {
                object obj = ResourceManager.GetObject("wget", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10100600
        ///	16
        ///10100D00
        ///	112
        ///	16
        ///	49
        ///	64
        ///	80
        ///	96
        ///10101A00
        ///	0
        ///10101B00
        ///	0
        ///	16
        ///10101C00
        ///	32
        ///	48
        ///	65
        ///10101D00
        ///	32
        ///	48
        ///	64
        ///10101E00
        ///	32
        ///	48
        ///	80
        ///10101F00
        ///	32
        ///10102000
        ///	32
        ///10102100
        ///	32
        ///10102200
        ///	32
        ///	48
        ///	64
        ///	81
        ///10102300
        ///	48
        ///	64
        ///	81
        ///10102400
        ///	16
        ///	48
        ///	64
        ///	81
        ///10102500
        ///	32
        ///	49
        ///	65
        ///	80
        ///	96
        ///10102900
        ///	18
        ///	32
        ///10102A00
        ///	19
        ///	48
        ///10102D00
        ///	16
        ///	32
        ///	48
        ///	80
        ///10102E00
        ///	16
        ///10102F00
        ///	16
        ///	32
        ///10104C00
        ///	48
        ///10104D00
        ///	0
        ///	16
        ///	32
        ///	48
        ///	65
        ///	80
        ///	96
        ///10105700
        ///	112
        ///	12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wiiu_versionlist {
            get {
                return ResourceManager.GetString("wiiu_versionlist", resourceCulture);
            }
        }
    }
}
