//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUSGrabberGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUSGrabberGUI.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new file or overwrite the current one.  Please don&apos;t mess with the program&apos;s directories IN THE MIDDLE of an important operation!  You&apos;ll have to redownload the versionlists again if you want to save them..
        /// </summary>
        internal static string access_error {
            get {
                return ResourceManager.GetString("access_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write unsuccessful.  Keeping versionlists in memory until next reload..
        /// </summary>
        internal static string access_error_debug {
            get {
                return ResourceManager.GetString("access_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-decrypting title..
        /// </summary>
        internal static string auto_decrypt_debug {
            get {
                return ResourceManager.GetString("auto_decrypt_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad versionlist .
        /// </summary>
        internal static string bad_vl_debug {
            get {
                return ResourceManager.GetString("bad_vl_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t access .
        /// </summary>
        internal static string cant_access_debug {
            get {
                return ResourceManager.GetString("cant_access_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for deletion..
        /// </summary>
        internal static string cant_access2_debug {
            get {
                return ResourceManager.GetString("cant_access2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t remove folder after deletion.  Ensure there is no other data in .
        /// </summary>
        internal static string cant_del_folder {
            get {
                return ResourceManager.GetString("cant_del_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete directory.
        /// </summary>
        internal static string cant_del_folder_debug {
            get {
                return ResourceManager.GetString("cant_del_folder_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and try again..
        /// </summary>
        internal static string cant_del_folder2 {
            get {
                return ResourceManager.GetString("cant_del_folder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up unneeded resource: .
        /// </summary>
        internal static string clean_debug {
            get {
                return ResourceManager.GetString("clean_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected that NUSGrabber.exe has closed with exit code of .
        /// </summary>
        internal static string close_code_debug {
            get {
                return ResourceManager.GetString("close_code_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  Preforming after-processing..
        /// </summary>
        internal static string close_code2_debug {
            get {
                return ResourceManager.GetString("close_code2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Overwrite.
        /// </summary>
        internal static string confirm_overwrite {
            get {
                return ResourceManager.GetString("confirm_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Update.
        /// </summary>
        internal static string confirm_update {
            get {
                return ResourceManager.GetString("confirm_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the internet.  Make sure you have internet access before loading titles!.
        /// </summary>
        internal static string connect_error {
            get {
                return ResourceManager.GetString("connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the internet.  Not loading titles..
        /// </summary>
        internal static string connect_error_debug {
            get {
                return ResourceManager.GetString("connect_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the Internet....
        /// </summary>
        internal static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to .
        /// </summary>
        internal static string connecting_debug {
            get {
                return ResourceManager.GetString("connecting_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem converting the selected item.  Note your selected item, contact FoxMcloud5655 on GBATemp, and tell him to look into this problem!.
        /// </summary>
        internal static string convert_error {
            get {
                return ResourceManager.GetString("convert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting title name into a ListItem..
        /// </summary>
        internal static string convert_error_debug {
            get {
                return ResourceManager.GetString("convert_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy common key.  Ensure you have access to read and write to the directory that you specified and that your common key actually exists..
        /// </summary>
        internal static string copy_ckey_error {
            get {
                return ResourceManager.GetString("copy_ckey_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t copy common key to .
        /// </summary>
        internal static string copy_ckey_error_debug {
            get {
                return ResourceManager.GetString("copy_ckey_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy files.  Ensure you have access to read and write to the directory that you specified and that CDecrypt.exe is in the root directory of the directory that this program is stored in..
        /// </summary>
        internal static string copy_files_error {
            get {
                return ResourceManager.GetString("copy_files_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy CDecrypt.exe to .
        /// </summary>
        internal static string copy_files_error_debug {
            get {
                return ResourceManager.GetString("copy_files_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy saved common key.  Ensure you have access to read and write to the directory that you specified..
        /// </summary>
        internal static string copy_saved_ckey_error {
            get {
                return ResourceManager.GetString("copy_saved_ckey_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t copy saved common key to .
        /// </summary>
        internal static string copy_saved_ckey_error_debug {
            get {
                return ResourceManager.GetString("copy_saved_ckey_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DEBUG.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write debug log.  Make sure you don&apos;t have it open somewhere and that you have write access to the root directory that this program is stored in..
        /// </summary>
        internal static string debug_log_error {
            get {
                return ResourceManager.GetString("debug_log_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  started in debug mode on .
        /// </summary>
        internal static string debug_start {
            get {
                return ResourceManager.GetString("debug_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  started in emulated debug mode on .
        /// </summary>
        internal static string debug_start_emu {
            get {
                return ResourceManager.GetString("debug_start_emu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting....
        /// </summary>
        internal static string decrypting {
            get {
                return ResourceManager.GetString("decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting decryption..
        /// </summary>
        internal static string decrypting_debug {
            get {
                return ResourceManager.GetString("decrypting_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting previously downloaded files by user request..
        /// </summary>
        internal static string deleting_debug {
            get {
                return ResourceManager.GetString("deleting_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current version is .
        /// </summary>
        internal static string dl_update {
            get {
                return ResourceManager.GetString("dl_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and the newest version is .
        /// </summary>
        internal static string dl_update2 {
            get {
                return ResourceManager.GetString("dl_update2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already up to date.  .
        /// </summary>
        internal static string dl_update3 {
            get {
                return ResourceManager.GetString("dl_update3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update.
        /// </summary>
        internal static string dl_update4 {
            get {
                return ResourceManager.GetString("dl_update4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  anyways.
        /// </summary>
        internal static string dl_update5 {
            get {
                return ResourceManager.GetString("dl_update5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t rename the .exe!  Please change it back to NEW-NUSGrabberGUI.exe!.
        /// </summary>
        internal static string dont_rename {
            get {
                return ResourceManager.GetString("dont_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading: .
        /// </summary>
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading...  Please wait..
        /// </summary>
        internal static string downloading_wait {
            get {
                return ResourceManager.GetString("downloading_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown problem while decrypting..
        /// </summary>
        internal static string error_cdecrypt {
            get {
                return ResourceManager.GetString("error_cdecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Decryption unsuccessful..
        /// </summary>
        internal static string error_cdecrypt_debug {
            get {
                return ResourceManager.GetString("error_cdecrypt_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking for the newest version..
        /// </summary>
        internal static string error_check_update {
            get {
                return ResourceManager.GetString("error_check_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t determine the newest version..
        /// </summary>
        internal static string error_check_update_debug {
            get {
                return ResourceManager.GetString("error_check_update_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete resource:.
        /// </summary>
        internal static string error_clean_debug {
            get {
                return ResourceManager.GetString("error_clean_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set working directory.  Ensure you have access to read and write to the directory that you specified..
        /// </summary>
        internal static string error_dir {
            get {
                return ResourceManager.GetString("error_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t set working directory to target directory..
        /// </summary>
        internal static string error_dir_debug {
            get {
                return ResourceManager.GetString("error_dir_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download the update.  You can still manually update from here:\nhttps://dl.dropboxusercontent.com/u/41125193/NUSGrabber/NEW-NUSGrabberGUI.exe\nThe program will now exit..
        /// </summary>
        internal static string error_dl_update {
            get {
                return ResourceManager.GetString("error_dl_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download.  Exiting..
        /// </summary>
        internal static string error_dl_update_debug {
            get {
                return ResourceManager.GetString("error_dl_update_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected: MSVRC120.dll not found.  Please install Visual C++ x86..
        /// </summary>
        internal static string error_dll_cdecrypt {
            get {
                return ResourceManager.GetString("error_dll_cdecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected: MSVRC120.dll not found..
        /// </summary>
        internal static string error_dll_cdecrypt_debug {
            get {
                return ResourceManager.GetString("error_dll_cdecrypt_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the internet to check for updates..
        /// </summary>
        internal static string error_internet_update {
            get {
                return ResourceManager.GetString("error_internet_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the internet to check for updates..
        /// </summary>
        internal static string error_internet_update_debug {
            get {
                return ResourceManager.GetString("error_internet_update_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No titles in titlelist.  Disabling UI and showing reload button..
        /// </summary>
        internal static string error_no_titles_debug {
            get {
                return ResourceManager.GetString("error_no_titles_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename the exe back.  Program will now exit, and you&apos;ll need to rename it yourself..
        /// </summary>
        internal static string error_rename_update {
            get {
                return ResourceManager.GetString("error_rename_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename self back to normal..
        /// </summary>
        internal static string error_rename_update_debug {
            get {
                return ResourceManager.GetString("error_rename_update_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart program. You&apos;ll need to exit and delete the old version, then load the program again..
        /// </summary>
        internal static string error_restart_update {
            get {
                return ResourceManager.GetString("error_restart_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart..
        /// </summary>
        internal static string error_restart_update_debug {
            get {
                return ResourceManager.GetString("error_restart_update_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem starting CDecrypt.  Ensure you have permission to execute files in the directory that you specified..
        /// </summary>
        internal static string error_start_cdecrypt {
            get {
                return ResourceManager.GetString("error_start_cdecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to start .
        /// </summary>
        internal static string error_start_cdecrypt_debug {
            get {
                return ResourceManager.GetString("error_start_cdecrypt_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem starting NUSgrabber.  Ensure that you have NUSgrabber in the root directory that this program is stored in..
        /// </summary>
        internal static string error_start_nus {
            get {
                return ResourceManager.GetString("error_start_nus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting NUSGrabber.exe..
        /// </summary>
        internal static string error_start_nus_debug {
            get {
                return ResourceManager.GetString("error_start_nus_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename old exe.  You&apos;ll need to manually update from here:\nhttps://dl.dropboxusercontent.com/u/41125193/NUSGrabber/NEW-NUSGrabberGUI.exe.
        /// </summary>
        internal static string error_update {
            get {
                return ResourceManager.GetString("error_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename self..
        /// </summary>
        internal static string error_update_debug {
            get {
                return ResourceManager.GetString("error_update_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  Extracting resource..
        /// </summary>
        internal static string extract_debug {
            get {
                return ResourceManager.GetString("extract_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t extract/read base files.  Make sure this program has read/write access to the directory it&apos;s stored in..
        /// </summary>
        internal static string extract_error {
            get {
                return ResourceManager.GetString("extract_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting resources..
        /// </summary>
        internal static string extract_error_debug {
            get {
                return ResourceManager.GetString("extract_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  Extracting default versionlist..
        /// </summary>
        internal static string extract_vl_debug {
            get {
                return ResourceManager.GetString("extract_vl_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected that NUSGrabber didn&apos;t run.  Install Visual Studio C++ (x86) and try again..
        /// </summary>
        internal static string failed_run {
            get {
                return ResourceManager.GetString("failed_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected that NUSGrabber didn&apos;t run.  Installation of Visual Studio C++ x86 (32-bit) is required.\nStatus Code: STATUS_INVALID_IMAGE_FORMAT.
        /// </summary>
        internal static string failed_run_debug {
            get {
                return ResourceManager.GetString("failed_run_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete download detected.  Delete &quot;.
        /// </summary>
        internal static string incomplete {
            get {
                return ResourceManager.GetString("incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible incomplete download..
        /// </summary>
        internal static string incomplete_debug {
            get {
                return ResourceManager.GetString("incomplete_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete download detected.  Deleting previous files..
        /// </summary>
        internal static string incomplete_dl_debug {
            get {
                return ResourceManager.GetString("incomplete_dl_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; and try downloading the title again..
        /// </summary>
        internal static string incomplete2 {
            get {
                return ResourceManager.GetString("incomplete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string latest {
            get {
                return ResourceManager.GetString("latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Versionlists....
        /// </summary>
        internal static string load_vl {
            get {
                return ResourceManager.GetString("load_vl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed load successfully..
        /// </summary>
        internal static string load_vl_complete_debug {
            get {
                return ResourceManager.GetString("load_vl_complete_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started load of versionlists..
        /// </summary>
        internal static string load_vl_debug {
            get {
                return ResourceManager.GetString("load_vl_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error while loading the version list!.
        /// </summary>
        internal static string load_vl_error {
            get {
                return ResourceManager.GetString("load_vl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error ocurred while trying to load wiiu_versionlist.txt.  Skipping load..
        /// </summary>
        internal static string load_vl_error_debug {
            get {
                return ResourceManager.GetString("load_vl_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titlelist already in memory.  Skipping load..
        /// </summary>
        internal static string load_vl_loaded {
            get {
                return ResourceManager.GetString("load_vl_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The versionlist file was modified externally.  Either fix it or redownload it..
        /// </summary>
        internal static string load_vl_modified {
            get {
                return ResourceManager.GetString("load_vl_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiiu_versionlist.txt was modified externally.  Skipping load..
        /// </summary>
        internal static string load_vl_modified_debug {
            get {
                return ResourceManager.GetString("load_vl_modified_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiiu_versionlist.txt not found.  Skipping load..
        /// </summary>
        internal static string load_vl_not_found_debug {
            get {
                return ResourceManager.GetString("load_vl_not_found_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting new version and exiting..
        /// </summary>
        internal static string new_version_debug {
            get {
                return ResourceManager.GetString("new_version_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common key was already part of .
        /// </summary>
        internal static string no_del_ckey_debug {
            get {
                return ResourceManager.GetString("no_del_ckey_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  Skipping removal..
        /// </summary>
        internal static string no_del_ckey2_debug {
            get {
                return ResourceManager.GetString("no_del_ckey2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate a .dll file.  Perhaps you are running WINE?.
        /// </summary>
        internal static string no_dll {
            get {
                return ResourceManager.GetString("no_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected that NUSGrabber didn&apos;t run.  Unable to find a required .dll.\nStatus Code: STATUS_DLL_NOT_FOUND.
        /// </summary>
        internal static string no_dll_debug {
            get {
                return ResourceManager.GetString("no_dll_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title successfully downloaded, but no decryption key was found.  Can&apos;t decrypt automatically..
        /// </summary>
        internal static string no_key {
            get {
                return ResourceManager.GetString("no_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find &quot;title.tik&quot;.  Skipping auto-decryption.\nTitle downloaded successfully..
        /// </summary>
        internal static string no_key_debug {
            get {
                return ResourceManager.GetString("no_key_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set your region in the settings before selecting this option!.
        /// </summary>
        internal static string no_region {
            get {
                return ResourceManager.GetString("no_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &quot;title.tik&quot;.  Did you download a full title?  Ensure you have this file in the directory that you specified..
        /// </summary>
        internal static string no_tik {
            get {
                return ResourceManager.GetString("no_tik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &quot;title.tmd&quot;.  Ensure this is truly a WiiU title..
        /// </summary>
        internal static string no_tmd {
            get {
                return ResourceManager.GetString("no_tmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not found..
        /// </summary>
        internal static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find .
        /// </summary>
        internal static string not_found_debug {
            get {
                return ResourceManager.GetString("not_found_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not implemented yet.  Select a game update or full title instead..
        /// </summary>
        internal static string not_implemented {
            get {
                return ResourceManager.GetString("not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse complete.  Writing data to wiiu_versionlist.txt..
        /// </summary>
        internal static string parse_complete_debug {
            get {
                return ResourceManager.GetString("parse_complete_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse data.  Either you aren&apos;t connected to the internet, or Nintendo has changed their format..
        /// </summary>
        internal static string parse_error {
            get {
                return ResourceManager.GetString("parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve/parse data from.
        /// </summary>
        internal static string parse_error_debug {
            get {
                return ResourceManager.GetString("parse_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Data....
        /// </summary>
        internal static string parsing_data {
            get {
                return ResourceManager.GetString("parsing_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing data gathered from .
        /// </summary>
        internal static string parsing_data_debug {
            get {
                return ResourceManager.GetString("parsing_data_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing list .
        /// </summary>
        internal static string parsing_list {
            get {
                return ResourceManager.GetString("parsing_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving list .
        /// </summary>
        internal static string parsing_list_debug {
            get {
                return ResourceManager.GetString("parsing_list_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string parsing_list2 {
            get {
                return ResourceManager.GetString("parsing_list2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of .
        /// </summary>
        internal static string parsing_list2_debug {
            get {
                return ResourceManager.GetString("parsing_list2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for .
        /// </summary>
        internal static string parsing_list3 {
            get {
                return ResourceManager.GetString("parsing_list3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from .
        /// </summary>
        internal static string parsing_list3_debug {
            get {
                return ResourceManager.GetString("parsing_list3_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumed path to the downloaded files is .
        /// </summary>
        internal static string path_debug {
            get {
                return ResourceManager.GetString("path_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already downloaded this title.  Are you sure you wish to redownload it?.
        /// </summary>
        internal static string redownload_title {
            get {
                return ResourceManager.GetString("redownload_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to rename original file - try #.
        /// </summary>
        internal static string rename_debug {
            get {
                return ResourceManager.GetString("rename_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing NUSgrabber.exe with .
        /// </summary>
        internal static string replace_nus_debug {
            get {
                return ResourceManager.GetString("replace_nus_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original.
        /// </summary>
        internal static string replace_nus2_debug {
            get {
                return ResourceManager.GetString("replace_nus2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hacked.
        /// </summary>
        internal static string replace_nus3_debug {
            get {
                return ResourceManager.GetString("replace_nus3_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  version..
        /// </summary>
        internal static string replace_nus4_debug {
            get {
                return ResourceManager.GetString("replace_nus4_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preforming shut down process..
        /// </summary>
        internal static string shut_down_debug {
            get {
                return ResourceManager.GetString("shut_down_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort complete..
        /// </summary>
        internal static string sort_complete_debug {
            get {
                return ResourceManager.GetString("sort_complete_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Titles....
        /// </summary>
        internal static string sorting_titles {
            get {
                return ResourceManager.GetString("sorting_titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse complete.  Sorting internal titlelist..
        /// </summary>
        internal static string sorting_titles_debug {
            get {
                return ResourceManager.GetString("sorting_titles_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting background download using libWiiSharp with .
        /// </summary>
        internal static string start_alt_dl_debug {
            get {
                return ResourceManager.GetString("start_alt_dl_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while trying to run the embeded NUSGrabber..
        /// </summary>
        internal static string start_alt_dl_error {
            get {
                return ResourceManager.GetString("start_alt_dl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while running libWiiSharp:.
        /// </summary>
        internal static string start_alt_dl_error_debug {
            get {
                return ResourceManager.GetString("start_alt_dl_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string start_alt_dl2_debug {
            get {
                return ResourceManager.GetString("start_alt_dl2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as arguments..
        /// </summary>
        internal static string start_alt_dl3_debug {
            get {
                return ResourceManager.GetString("start_alt_dl3_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting .
        /// </summary>
        internal static string starting_debug {
            get {
                return ResourceManager.GetString("starting_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with .
        /// </summary>
        internal static string starting2_debug {
            get {
                return ResourceManager.GetString("starting2_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  as arguments..
        /// </summary>
        internal static string starting3_debug {
            get {
                return ResourceManager.GetString("starting3_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title successfully decrypted..
        /// </summary>
        internal static string success_decrypt {
            get {
                return ResourceManager.GetString("success_decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption successful..
        /// </summary>
        internal static string success_decrypt_debug {
            get {
                return ResourceManager.GetString("success_decrypt_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title successfully downloaded..
        /// </summary>
        internal static string success_dl {
            get {
                return ResourceManager.GetString("success_dl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title downloaded successfully..
        /// </summary>
        internal static string success_dl_debug {
            get {
                return ResourceManager.GetString("success_dl_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title ID:.
        /// </summary>
        internal static string title_id {
            get {
                return ResourceManager.GetString("title_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Name: .
        /// </summary>
        internal static string title_name {
            get {
                return ResourceManager.GetString("title_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title not found on Nintendo&apos;s servers..
        /// </summary>
        internal static string title_not_found {
            get {
                return ResourceManager.GetString("title_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title not found..
        /// </summary>
        internal static string title_not_found_debug {
            get {
                return ResourceManager.GetString("title_not_found_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Region: .
        /// </summary>
        internal static string title_region {
            get {
                return ResourceManager.GetString("title_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Versions: .
        /// </summary>
        internal static string title_versions {
            get {
                return ResourceManager.GetString("title_versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown problem while downloading..
        /// </summary>
        internal static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred while downloading..
        /// </summary>
        internal static string unknown_error_debug {
            get {
                return ResourceManager.GetString("unknown_error_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Program.
        /// </summary>
        internal static string update_program {
            get {
                return ResourceManager.GetString("update_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully obtained update.  Application will now restart..
        /// </summary>
        internal static string update_success {
            get {
                return ResourceManager.GetString("update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful..
        /// </summary>
        internal static string update_success_debug {
            get {
                return ResourceManager.GetString("update_success_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update the VersionList for all titles in .
        /// </summary>
        internal static string update_vl {
            get {
                return ResourceManager.GetString("update_vl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?  This will take some time..
        /// </summary>
        internal static string update_vl2 {
            get {
                return ResourceManager.GetString("update_vl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUSGrabber exited without finishing the download.  Please do not exit NUSGrabber while it&apos;s downloading!.
        /// </summary>
        internal static string user_close {
            get {
                return ResourceManager.GetString("user_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User closed NUSGrabber.  Program exited without finishing download..
        /// </summary>
        internal static string user_close_debug {
            get {
                return ResourceManager.GetString("user_close_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a new file or overwrite the current one.  Ensure that you have permission to write to the root directory that this GUI is stored in..
        /// </summary>
        internal static string write_error {
            get {
                return ResourceManager.GetString("write_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open/create wiiu_versionlist.txt.  Skipping update..
        /// </summary>
        internal static string write_error_debug {
            get {
                return ResourceManager.GetString("write_error_debug", resourceCulture);
            }
        }
    }
}
